---
abstract: 'dzil plugin bundle of ZURBORG'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-ZURBORG
requires:
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Moose: '0'
  Pod::Weaver::Config::Assembler: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources: {}
version: '0.001'
x_contributors:
  - 'David Zurborg <port@david-zurb.org>'
